import { PrismaClient } from "@prisma/client"
import { PrismaPg } from "@prisma/adapter-pg"

const connectionString = process.env.DATABASE_URL

if (!connectionString) {
  throw new Error("DATABASE_URL is required to seed the database.")
}

const prisma = new PrismaClient({
  adapter: new PrismaPg({ connectionString }),
})

const skillTrees = [
  {
    slug: "data-engineering",
    label: "Data Engineering",
    className: "Data Wizard",
    blurb: "Bend databases and pipelines to your will.",
    icon: "brain",
    classColor: "INT",
    displayLevel: 5,
    primaryStat: "INT",
    npcRole: "WIZARD",
    sortOrder: 10,
    isStarter: true,
    quests: [
      {
        slug: "de-1",
        title: "Master PostgreSQL JOINs",
        description: "Write a SQL query using INNER JOIN and LEFT JOIN.",
        xpReward: 150,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "de-n3",
      },
      {
        slug: "de-2",
        title: "Index a Slow Query",
        description: "Add a B-tree index and measure the speedup with EXPLAIN.",
        xpReward: 90,
        nodeSlug: "de-n3",
      },
      {
        slug: "de-3",
        title: "Read the Docs",
        description: "Read 15 pages of the PostgreSQL internals manual.",
        xpReward: 50,
        nodeSlug: "de-n3",
      },
    ],
    nodes: [
      { slug: "de-n1", label: "Python Basics", statusDefault: "MASTERED", x: 8, y: 8, prereqs: [] },
      { slug: "de-n2", label: "SQL Fundamentals", statusDefault: "MASTERED", x: 200, y: 8, prereqs: [] },
      {
        slug: "de-n3",
        label: "PostgreSQL Internals",
        statusDefault: "ACTIVE",
        x: 200,
        y: 140,
        prereqs: ["de-n2"],
      },
      {
        slug: "de-n4",
        label: "SQLAlchemy ORM",
        statusDefault: "LOCKED",
        x: 104,
        y: 272,
        prereqs: ["de-n1", "de-n2"],
      },
      {
        slug: "de-n5",
        label: "Airflow Pipelines",
        statusDefault: "LOCKED",
        x: 200,
        y: 272,
        prereqs: ["de-n3"],
      },

      
    ],
  },
  {
    slug: "fitness",
    label: "Iron Foundry",
    className: "Iron Warrior",
    blurb: "Awaken your body, forge raw strength, and conquer the resistance.",
    icon: "dumbbell",
    classColor: "STR",
    displayLevel: 1,
    primaryStat: "STR",
    npcRole: "WARRIOR",
    sortOrder: 20,
    isStarter: true,
    quests: [
      // --- NODE 1: THE STARTING LINE (1 Quest) ---
      {
        slug: "fit-0-baseline",
        title: "Baseline Assessment",
        description: "Record your starting weight, waist, chest, and bicep measurements. Take a realistic 'Before' photo for your hidden vault.",
        xpReward: 100,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n1-start",
      },


      // --- NODE 2: ZERO TO ONE (20 Quests - Home Foundation) ---
      // Effort & Physics
      {
        slug: "fit-1-push",
        title: "The Floor is Yours",
        description: "Complete 50 push-ups throughout the day. Knee push-ups are perfectly fine. Focus on form, not speed.",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-squat",
        title: "Leg Drive (Home)",
        description: "Complete 100 bodyweight squats today. Keep your heels glued to the floor and back straight.",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-plank",
        title: "Core Ignition",
        description: "Accumulate 3 minutes of planking in a single day. Don't let your lower back sag.",
        xpReward: 60,
        goldReward: 5,
        hasAiHelper: true,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-pull",
        title: "Improvised Pull",
        description: "Do 3 sets of inverted rows using a very sturdy, heavy table. Safety first: test its stability before pulling your weight.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-cardio",
        title: "Cardio Explorer",
        description: "Walk 3 kilometers at a brisk pace without stopping. Breathe deep and clear your mind.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n2-zero",
      },
      
      // Habits & Consistency
      {
        slug: "fit-1-morning",
        title: "Morning Steel",
        description: "Do a 10-minute stretch routine immediately after waking up, before checking your phone.",
        xpReward: 50,
        goldReward: 0,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-streak",
        title: "Home Consistency",
        description: "Work out at home 3 times this week for at least 20 minutes each session.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-water",
        title: "Water Element",
        description: "Drink at least 2 liters of pure water daily for 3 consecutive days.",
        xpReward: 50,
        goldReward: 0,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-sugar",
        title: "No Sugar Day",
        description: "Survive one full day with zero added sugar, sweets, or sugary drinks.",
        xpReward: 60,
        goldReward: 5,
        hasAiHelper: true,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-protein",
        title: "Protein Awareness",
        description: "Eat 3 different sources of high-quality protein today (e.g., eggs, chicken, tofu).",
        xpReward: 50,
        goldReward: 0,
        nodeSlug: "fit-n2-zero",
      },

      // Mindset & Safety
      {
        slug: "fit-1-schedule",
        title: "The Blueprint",
        description: "Write down your exact workout days and times for the week. Stick to the first scheduled session.",
        xpReward: 50,
        goldReward: 0,
        hasAiHelper: true,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-focus",
        title: "Digital Detox",
        description: "Complete a 20-minute home workout with your phone in another room. No scrolling between sets.",
        xpReward: 50,
        goldReward: 0,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-recovery",
        title: "Active Recovery",
        description: "Do a 10-minute light stretching session the day after a workout to ease muscle soreness.",
        xpReward: 50,
        goldReward: 0,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-research",
        title: "Form Check",
        description: "Watch a tutorial on proper push-up form. Identify and correct one mistake you've been making.",
        xpReward: 40,
        goldReward: 0,
        hasAiHelper: true,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-adapt",
        title: "No Excuses",
        description: "Complete a workout in a space smaller than 2x2 meters. You don't need a gym to sweat.",
        xpReward: 50,
        goldReward: 5,
        nodeSlug: "fit-n2-zero",
      },

      // Milestones & Mini-Bosses
      {
        slug: "fit-1-perfect",
        title: "The Perfect Ten",
        description: "Perform 10 push-ups in a row with flawless form. Chest to the floor, body straight as a board.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-wallsit",
        title: "Static Hold",
        description: "Perform a wall sit with your legs at a 90-degree angle for 60 seconds straight. Embrace the burn.",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-lunges",
        title: "Balance & Control",
        description: "Complete 3 sets of 15 alternating lunges per leg. Step carefully and control the descent.",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-gauntlet",
        title: "The Gauntlet",
        description: "Pick one exercise (squats or crunches) and do 100 reps as fast as safely possible. Record your time.",
        xpReward: 90,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n2-zero",
      },
      {
        slug: "fit-1-graduation",
        title: "Ready for Iron",
        description: "Complete 3 sets of 15 push-ups and 30 squats in one session. You are now prepared for the next tier.",
        xpReward: 100,
        goldReward: 20,
        nodeSlug: "fit-n2-zero",
      },
      // ==========================================
      // --- NODE 3: THE PATH OF IRON (GYM) ---
      // ==========================================
      // Таймфрейм: ~1 місяць. Мета: адаптація до ваг, перші бліни на штанзі, стабільність.
      {
        slug: "fit-iron-1",
        kind: "MAIN",
        title: "The Iron Habit",
        description: "Complete 12 full gym workouts within a 30-day period. Consistency is your first real weight.",
        xpReward: 150,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-2",
        kind: "MAIN",
        title: "Logbook Scholar",
        description: "Log your exercises, sets, and weights for 3 consecutive weeks. You can't improve what you don't measure.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-3",
        kind: "MAIN",
        title: "Fuel the Machine",
        description: "Hit your daily protein target (approx. 1.6g per kg of bodyweight) for 10 days in a row.",
        xpReward: 100,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-4",
        kind: "MAIN",
        title: "Bench Press: First Plates",
        description: "Graduate from the empty bar. Bench press 30kg (a 5kg plate on each side) for 3 sets of 8 reps.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-5",
        kind: "MAIN",
        title: "Bench Press: The 40kg Mark",
        description: "Bench press 40kg (a 10kg plate on each side) for 5 clean reps. Feel the weight in your chest.",
        xpReward: 120,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-6",
        kind: "MAIN",
        title: "Squat: Depth & Control",
        description: "Barbell back squat 40kg for 3 sets of 8 reps. Your hips must go below your knees.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-7",
        kind: "MAIN",
        title: "Squat: The 50kg Milestone",
        description: "Squat 50kg for 5 solid reps. Keep your chest up and core tight.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-8",
        kind: "MAIN",
        title: "Deadlift Initiation",
        description: "Perform the conventional or sumo deadlift with 40kg for 3 sets of 5 reps. Learn the hip hinge.",
        xpReward: 80,
        goldReward: 10,
        hasAiHelper: true,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-9",
        kind: "MAIN",
        title: "Deadlift: The 60kg Pull",
        description: "Load the big 20kg plates. Deadlift 60kg for 3 clean reps with a perfectly straight back.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-10",
        kind: "MAIN",
        title: "Overhead Press Foundation",
        description: "Strict standing barbell press with the empty 20kg bar for 3 sets of 8 reps.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-11",
        kind: "MAIN",
        title: "Rowing for Width",
        description: "Perform barbell bent-over rows with 30kg for 4 sets of 10 reps. Squeeze your shoulder blades.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-12",
        kind: "MAIN",
        title: "Dumbbell Stability",
        description: "Perform flat dumbbell bench press using 12kg-14kg dumbbells in each hand for 3 sets of 10 reps.",
        xpReward: 90,
        goldReward: 15,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-13",
        kind: "MAIN",
        title: "Leg Press 100kg",
        description: "Load the leg press with 100kg (usually two 25kg plates per side) and complete 3 sets of 10 full reps.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-14",
        kind: "MAIN",
        title: "Farmer's Walk",
        description: "Hold a 16kg dumbbell in each hand and walk for 45 seconds without dropping them. Build your grip.",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-15",
        kind: "MAIN",
        title: "Lat Pulldown Progression",
        description: "Perform 3 sets of 10 on the lat pulldown machine using a weight that equals at least 50% of your body weight.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-16",
        kind: "MAIN",
        title: "The First Strict Dip",
        description: "Ditch the assistance machine. Perform 1 to 3 strict bodyweight dips on the parallel bars.",
        xpReward: 90,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-17",
        kind: "MAIN",
        title: "Bicep Pump",
        description: "Perform standing dumbbell bicep curls with 10kg-12kg dumbbells for 3 sets of 10 reps (per arm).",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-18",
        kind: "MAIN",
        title: "Tricep Pump",
        description: "Complete 3 sets of 15 reps on the cable tricep pushdown. Feel the burn and control the negative.",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-19",
        kind: "MAIN",
        title: "Form Check Video",
        description: "Record yourself doing a set of squats or deadlifts. Review the footage to find one technical flaw to fix.",
        xpReward: 50,
        goldReward: 5,
        hasAiHelper: true,
        nodeSlug: "fit-n3-iron",
      },
      {
        slug: "fit-iron-20",
        kind: "MAIN",
        title: "The 1-Month PR Check",
        description: "Test yourself safely. Successfully lift a weight you couldn't lift on your first day in any compound exercise.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n3-iron",
      },

      // ==========================================
      // --- NODE 4: THE PATH OF GRAVITY (CALISTHENICS) ---
      // ==========================================
      // Таймфрейм: ~1 місяць. Мета: підкорити вагу власного тіла, вийти на перші підтягування і бруси.
      {
        slug: "fit-cali-1",
        kind: "MAIN",
        title: "The Gravity Habit",
        description: "Complete 12 intense calisthenics workouts (outdoor park or home) within a 30-day period.",
        xpReward: 150,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-2",
        kind: "MAIN",
        title: "Push-up Endurance",
        description: "Accumulate 200 push-ups over the course of a single week.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-3",
        kind: "MAIN",
        title: "Unbroken Push-ups: 25",
        description: "Perform 25 strict push-ups in a single, unbroken set. Chest to the floor.",
        xpReward: 90,
        goldReward: 10,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-4",
        kind: "MAIN",
        title: "The One-Minute Hang",
        description: "Hang from a pull-up bar for 60 seconds straight without letting go. Build that grip.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-5",
        kind: "MAIN",
        title: "Negative Pull-up Mastery",
        description: "Jump to the top of the bar and lower yourself slowly (3-5 seconds). Do 3 sets of 5 reps.",
        xpReward: 90,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-6",
        kind: "MAIN",
        title: "The First Strict Pull-up",
        description: "The ultimate milestone. Perform 1 strict, dead-hang pull-up. Chin over the bar, no kicking.",
        xpReward: 150,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-7",
        kind: "MAIN",
        title: "Pull-up Triple",
        description: "Perform 3 strict pull-ups in a single set. You are officially pulling your own weight.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-8",
        kind: "MAIN",
        title: "The First Dip",
        description: "Jump onto the parallel bars and perform 1 to 3 strict dips. Go down until your elbows are at 90 degrees.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-9",
        kind: "MAIN",
        title: "Dip Progression",
        description: "Perform 3 sets of 5 dips. Keep your core tight and lean slightly forward for chest activation.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-10",
        kind: "MAIN",
        title: "Pike Push-ups",
        description: "Get into a V-shape (hips high) and do 3 sets of 8 pike push-ups. Build your shoulder strength.",
        xpReward: 80,
        goldReward: 10,
        hasAiHelper: true,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-11",
        kind: "MAIN",
        title: "Explosive Jump Squats",
        description: "Do 3 sets of 15 jump squats. Explode as high as you can and land softly to protect your knees.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-12",
        kind: "MAIN",
        title: "Bulgarian Split Squats",
        description: "Elevate your rear foot on a bench. Do 3 sets of 10 reps per leg. The king of bodyweight leg exercises.",
        xpReward: 90,
        goldReward: 15,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-13",
        kind: "MAIN",
        title: "Knees to Chest",
        description: "Hang from the bar and use your core to lift your knees to your chest. 3 sets of 10 reps.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-14",
        kind: "MAIN",
        title: "Hollow Body Hold",
        description: "Hold the hollow body position (lower back glued to the floor) for 45 seconds unbroken.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-15",
        kind: "MAIN",
        title: "Diamond Push-ups",
        description: "Hands together forming a diamond shape. Do 3 sets of 10 reps to target the triceps.",
        xpReward: 70,
        goldReward: 10,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-16",
        kind: "MAIN",
        title: "Outdoor Warrior",
        description: "Complete a full workout outside when the weather is less than ideal (rain, cold, or early morning).",
        xpReward: 60,
        goldReward: 5,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-17",
        kind: "MAIN",
        title: "The 300 Squat Week",
        description: "Accumulate 300 bodyweight squats over the course of 7 days.",
        xpReward: 90,
        goldReward: 15,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-18",
        kind: "MAIN",
        title: "Fuel for Flight",
        description: "Hit your daily protein and calorie targets for 7 consecutive days to fuel muscle recovery.",
        xpReward: 100,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-19",
        kind: "MAIN",
        title: "Wide Grip Pull-ups",
        description: "If you can do regular pull-ups, perform 3 sets of 3 with a wide grip to target the lats.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n4-gravity",
      },
      {
        slug: "fit-cali-20",
        kind: "MAIN",
        title: "The Calisthenics Circuit",
        description: "Do this for time: 3 Pull-ups, 5 Dips, 15 Push-ups, 20 Squats. Rest 2 mins. Repeat 3 times.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n4-gravity",
      },
      // ==========================================
      // --- NODE 5: THE PPL PROTOCOL (ADVANCED IRON) ---
      // ==========================================
      // Таймфрейм: 1.5 - 2 місяці. Фокус на гіпертрофії, спеціалізації та базових рекордах.
      {
        slug: "fit-ppl-1",
        kind: "MAIN",
        title: "The Push Day",
        description: "Complete a dedicated Push workout (Chest, Shoulders, Triceps). Heavy presses first, isolations last.",
        xpReward: 90,
        goldReward: 10,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-2",
        kind: "MAIN",
        title: "The Pull Day",
        description: "Complete a dedicated Pull workout (Back, Biceps, Rear Delts). Focus on pulling with your back, not your arms.",
        xpReward: 90,
        goldReward: 10,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-3",
        kind: "MAIN",
        title: "The Leg Day",
        description: "Complete a dedicated Leg workout (Quads, Hamstrings, Calves). Don't skip it, even if it hurts to walk tomorrow.",
        xpReward: 100,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-4",
        kind: "MAIN",
        title: "The 6-Day Grind",
        description: "Run the full PPL cycle twice in a single week (Push, Pull, Legs, Push, Pull, Legs). Test your recovery limits.",
        xpReward: 200,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-5",
        kind: "MAIN",
        title: "Bench Press: The 60kg Milestone",
        description: "The classic plate milestone. Load one 20kg plate on each side. Bench 60kg for at least 1 clean rep.",
        xpReward: 150,
        goldReward: 25,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-6",
        kind: "MAIN",
        title: "Incline Specialist",
        description: "Perform incline dumbbell press (30-45 degrees) with at least 16kg dumbbells for 3 sets of 10. Build the upper chest.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-7",
        kind: "MAIN",
        title: "Squat: The 80kg Milestone",
        description: "Load the bar to 80kg. Squat deep (hips below knees) for at least 1 solid rep.",
        xpReward: 150,
        goldReward: 25,
        hasAiHelper: true,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-8",
        kind: "MAIN",
        title: "Romanian Deadlifts (RDL)",
        description: "Perform 3 sets of 10 RDLs with 60kg. Push your hips back and feel the massive stretch in your hamstrings.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-9",
        kind: "MAIN",
        title: "Deadlift: The 100kg Milestone",
        description: "Two 20kg plates on each side. Deadlift 100kg for 1 rep. Lock it out proudly. You are now officially lifting heavy.",
        xpReward: 200,
        goldReward: 40,
        hasAiHelper: true,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-10",
        kind: "MAIN",
        title: "Shoulder Boulders",
        description: "Strict standing military press with 40kg (a 10kg plate on each side) for 3 sets of 5 reps.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-11",
        kind: "MAIN",
        title: "Barbell Row Power",
        description: "Perform barbell bent-over rows with 60kg for 3 sets of 8 reps. Pull the bar to your belly button.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-12",
        kind: "MAIN",
        title: "The Weighted Pull-up",
        description: "Attach a 5kg or 10kg plate to a dip belt (or hold a dumbbell between your feet) and perform 3 strict pull-ups.",
        xpReward: 130,
        goldReward: 20,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-13",
        kind: "MAIN",
        title: "The Pump (Supersets)",
        description: "Do a bicep curl immediately followed by a tricep extension with no rest (a superset). Do 3 rounds. Feel your arms swell.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-14",
        kind: "MAIN",
        title: "Don't Skip Calves",
        description: "Perform 4 sets of 15 standing or seated calf raises with a heavy weight and a slow, controlled negative.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-15",
        kind: "MAIN",
        title: "Leg Press: 150kg",
        description: "Load the leg press with 150kg and rep it out for 3 sets of 10. Don't lock your knees out!",
        xpReward: 110,
        goldReward: 15,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-16",
        kind: "MAIN",
        title: "Dumbbell Press Progression",
        description: "Perform flat dumbbell bench press with 24kg dumbbells in each hand for at least 6 reps.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-17",
        kind: "MAIN",
        title: "Hypertrophy Fuel",
        description: "Consistently eat in a slight caloric surplus (200-300 extra calories) with high protein for 14 days straight.",
        xpReward: 100,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-18",
        kind: "MAIN",
        title: "The Social Spotter",
        description: "Ask a stronger person in the gym to spot you on a heavy bench press attempt. It builds community.",
        xpReward: 80,
        goldReward: 10,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-19",
        kind: "MAIN",
        title: "Deload Week",
        description: "Your nervous system needs a break. Spend one week lifting only 50% of your normal weights. Let your joints heal.",
        xpReward: 100,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n5-ppl",
      },
      {
        slug: "fit-ppl-20",
        kind: "MAIN",
        title: "PPL Graduate",
        description: "Successfully complete 4 full weeks (at least 12 sessions) of the PPL split. You are forging iron.",
        xpReward: 250,
        goldReward: 40,
        nodeSlug: "fit-n5-ppl",
      },
      // ==========================================
      // --- NODE 6: THE IRON VANGUARD (END-GAME) ---
      // ==========================================
      // Таймфрейм: 3-6 місяців і далі. Перевірка максимумів, екіпірування, хардкорні техніки.
      {
        slug: "fit-vanguard-1",
        kind: "MAIN",
        title: "Armor Up",
        description: "Invest in or borrow a lifting belt. Learn to perform the Valsalva maneuver to brace your core during heavy squats or deadlifts.",
        xpReward: 100,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-2",
        kind: "MAIN",
        title: "Titan's Grip",
        description: "Use lifting straps for the first time on heavy deadlifts, RDLs, or shrugs. Take your grip out of the equation and overload the back.",
        xpReward: 100,
        goldReward: 20,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-3",
        kind: "MAIN",
        title: "The Drop Set",
        description: "On a safe machine (like Leg Extensions or Cable Crunches), push to failure, drop the weight by 30%, and immediately push to failure again.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-4",
        kind: "MAIN",
        title: "Eccentric Overload",
        description: "Perform 3 sets of bench press or squats where the lowering phase (eccentric) takes exactly 4 painful seconds per rep.",
        xpReward: 120,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-5",
        kind: "MAIN",
        title: "Pause Squats",
        description: "Perform 3 sets of 5 reps with 70% of your max squat. Pause dead at the very bottom for 3 full seconds on every rep.",
        xpReward: 150,
        goldReward: 25,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-6",
        kind: "MAIN",
        title: "Bench Press: The 80kg Boss",
        description: "Load the bar to 80kg. Warm up properly, get a spotter, and hit at least 1 clean rep. You are stronger than most men now.",
        xpReward: 250,
        goldReward: 50,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-7",
        kind: "MAIN",
        title: "Squat: The 100kg Boss",
        description: "The 2-plate milestone. Load two 20kg plates on each side of the 20kg bar. Squat 100kg deep and rise up victorious.",
        xpReward: 300,
        goldReward: 60,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-8",
        kind: "MAIN",
        title: "Deadlift: The 120kg Pull",
        description: "Load 120kg on the bar. Set your back, brace your core, and pull it from the floor to lockout.",
        xpReward: 250,
        goldReward: 50,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-9",
        kind: "MAIN",
        title: "Strict OHP: The 50kg Press",
        description: "Overhead press 50kg strictly (no leg drive) for at least 1 rep. Shoulders of steel.",
        xpReward: 200,
        goldReward: 40,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-10",
        kind: "MAIN",
        title: "The Widowmaker",
        description: "A legendary test of will. Load the barbell with your 10-rep max weight, but do not rack it until you complete 20 reps. Breathe. Survive.",
        xpReward: 300,
        goldReward: 50,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-11",
        kind: "MAIN",
        title: "Rest-Pause Torment",
        description: "Pick a bicep or tricep exercise. Do reps to failure. Rest exactly 15 seconds. Rep to failure again. Rest 15s. Rep to failure once more.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-12",
        kind: "MAIN",
        title: "The 24kg Dumbbells",
        description: "Graduate to the heavy rack. Perform flat or incline bench press with at least 24kg dumbbells in each hand for 8 reps.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-13",
        kind: "MAIN",
        title: "Bulking or Cutting",
        description: "Choose a path: strictly eat in a 400-calorie surplus to build mass, or a 400-calorie deficit to shred fat, for 21 days straight.",
        xpReward: 200,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-14",
        kind: "MAIN",
        title: "Prehab & Mobility",
        description: "Your joints are taking a beating. Perform 15 minutes of dedicated rotator cuff and hip mobility work before 3 consecutive workouts.",
        xpReward: 100,
        goldReward: 15,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-15",
        kind: "MAIN",
        title: "Weighted Dips",
        description: "Attach 10kg to a dip belt and perform 3 sets of 8 strict parallel bar dips. Build the ultimate triceps.",
        xpReward: 150,
        goldReward: 25,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-16",
        kind: "MAIN",
        title: "The 100-Workout Veteran",
        description: "Log your 100th lifetime workout in the app. You are no longer trying to build a habit; this is who you are.",
        xpReward: 500,
        goldReward: 100,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-17",
        kind: "MAIN",
        title: "The Powerlifting Total",
        description: "Calculate your 1-Rep Max for Bench, Squat, and Deadlift. Add them together to get your Powerlifting Total. Log this number.",
        xpReward: 200,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-18",
        kind: "MAIN",
        title: "Mentor the Weak",
        description: "Give genuinely helpful advice to a beginner in the gym, or convince a friend to start working out.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-19",
        kind: "MAIN",
        title: "Absolute Failure",
        description: "With a spotter, perform a set of heavy bench presses until you literally cannot push the bar back up. Learn what true failure feels like.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-vanguard",
      },
      {
        slug: "fit-vanguard-20",
        kind: "MAIN",
        title: "The Vanguard Reveal",
        description: "Take a new physique photo. Place it side-by-side with your photo from 'Baseline Assessment' (Node 1). Acknowledge your transformation.",
        xpReward: 500,
        goldReward: 100,
        hasAiHelper: true,
        nodeSlug: "fit-n6-vanguard",
      },
      // ==========================================
      // --- NODE 5: THE GRAVITY MASTER (ADVANCED CALISTHENICS) ---
      // ==========================================
      // Таймфрейм: 3-6 місяців. Фокус на статиці, гімнастичних елементах та вибуховій силі.
      {
        slug: "fit-gravity-1",
        kind: "MAIN",
        title: "Lord of the Rings",
        description: "Purchase or find a set of gymnastic rings. Hang them up and perform a basic support hold (arms straight, shoulders down) for 30 seconds. Feel the instability.",
        xpReward: 100,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-2",
        kind: "MAIN",
        title: "Ring Dips",
        description: "Perform 3 sets of 8 strict dips on the gymnastic rings. Turn the rings outward at the top of every rep.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-3",
        kind: "MAIN",
        title: "Explosive High Pull",
        description: "Perform 3 pull-ups where you pull so hard and fast that the bar touches your stomach, not just your chest.",
        xpReward: 100,
        goldReward: 20,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-4",
        kind: "MAIN",
        title: "The Muscle-Up Transition",
        description: "Practice the 'Russian Dip' on parallel bars or do straight-bar dips to build the pushing strength needed for the muscle-up transition.",
        xpReward: 100,
        goldReward: 15,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-5",
        kind: "MAIN",
        title: "The First Muscle-Up",
        description: "The ultimate street milestone. Combine the explosive pull and the transition. Perform 1 strict or slightly kipped Muscle-Up on the bar.",
        xpReward: 300,
        goldReward: 60,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-6",
        kind: "MAIN",
        title: "Freestanding Handstand",
        description: "Kick up into a handstand without a wall and hold it for 10 seconds. Use your fingers to balance.",
        xpReward: 150,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-7",
        kind: "MAIN",
        title: "Wall Handstand Push-ups (HSPU)",
        description: "Kick up against a wall. Lower your head to the floor and press back up. Complete 3 sets of 5 reps.",
        xpReward: 150,
        goldReward: 25,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-8",
        kind: "MAIN",
        title: "The One-Arm Push-up",
        description: "Spread your legs wide, put one hand behind your back, and perform 1 clean push-up per arm. Channel your inner Rocky.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-9",
        kind: "MAIN",
        title: "L-Sit Mastery",
        description: "Hold a perfect L-Sit (legs locked out straight) on the floor or parallettes for 30 uninterrupted seconds.",
        xpReward: 120,
        goldReward: 20,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-10",
        kind: "MAIN",
        title: "Skin the Cat",
        description: "Hang from the bar or rings, pull your legs through your arms, and lower into a deep shoulder stretch (German Hang), then pull back over.",
        xpReward: 120,
        goldReward: 25,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-11",
        kind: "MAIN",
        title: "Tuck Front Lever",
        description: "Hang from the bar, tuck your knees to your chest, and lean back until your torso is parallel to the ground. Hold for 15 seconds.",
        xpReward: 100,
        goldReward: 20,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-12",
        kind: "MAIN",
        title: "Advanced Tuck Front Lever",
        description: "Same as the tuck lever, but extend your knees until your back is perfectly flat (90-degree hip angle). Hold for 10 seconds. Core of iron.",
        xpReward: 150,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-13",
        kind: "MAIN",
        title: "Back Lever Prep",
        description: "Perform a Tuck Back Lever. Hang upside down and lower your body facing the floor with knees tucked. Hold for 15s.",
        xpReward: 100,
        goldReward: 20,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-14",
        kind: "MAIN",
        title: "Typewriter Pull-ups",
        description: "Pull up above the bar, shift your body entirely to the left hand, then to the right hand, then lower. Do 3 reps per side.",
        xpReward: 150,
        goldReward: 25,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-15",
        kind: "MAIN",
        title: "True Pistol Squat",
        description: "Perform 5 unassisted, deep pistol squats per leg. Your mobility and single-leg strength are now elite.",
        xpReward: 150,
        goldReward: 25,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-16",
        kind: "MAIN",
        title: "Weighted Calisthenics: Pull",
        description: "Strap a 16kg kettlebell or plate to your waist. Perform 3 strict pull-ups. Gravity is losing its grip on you.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-17",
        kind: "MAIN",
        title: "Weighted Calisthenics: Push",
        description: "Strap 24kg to your waist. Perform 5 strict parallel bar dips.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-18",
        kind: "MAIN",
        title: "Human Flag Foundation",
        description: "Find a vertical pole. Perform a 'Clutch Flag' (hugging the pole) and hold your body horizontal for 10 seconds.",
        xpReward: 120,
        goldReward: 20,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-19",
        kind: "MAIN",
        title: "The 100-Rep Gauntlet",
        description: "Perform 100 strict pull-ups in a single workout. It doesn't matter how many sets it takes. Finish it.",
        xpReward: 300,
        goldReward: 50,
        nodeSlug: "fit-n5-gravity_master",
      },
      {
        slug: "fit-gravity-20",
        kind: "MAIN",
        title: "Airbender Reveal",
        description: "Record a video of your most advanced static skill (Muscle-up, Handstand, or Lever). Place it next to your day 1 photo. You have mastered your own weight.",
        xpReward: 500,
        goldReward: 100,
        hasAiHelper: true,
        nodeSlug: "fit-n5-gravity_master",
      },
      // ==========================================
      // --- NODE 6: THE ASCENDANT (END-GAME CALISTHENICS) ---
      // ==========================================
      // Таймфрейм: 6-12 місяців і більше. Елітні статичні елементи, мутантська сила на одну руку.
      {
        slug: "fit-ascendant-1",
        kind: "MAIN",
        title: "Ring Muscle-Up",
        description: "Perform 1 strict Muscle-Up on the gymnastic rings. The ultimate test of upper body synchronization and false grip.",
        xpReward: 200,
        goldReward: 40,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-2",
        kind: "MAIN",
        title: "Tuck Planche",
        description: "Place your hands on the floor or parallettes. Lean forward and lift your entire body off the ground with knees tucked. Hold for 15 seconds.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-3",
        kind: "MAIN",
        title: "Straddle Planche Prep",
        description: "Open your legs wide (straddle) and attempt to hold your body parallel to the ground, supported only by your hands, for 3 seconds.",
        xpReward: 300,
        goldReward: 60,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-4",
        kind: "MAIN",
        title: "Full Back Lever",
        description: "Hang from the rings or bar, lower yourself facing the floor with your body perfectly straight. Hold for 5 seconds.",
        xpReward: 200,
        goldReward: 40,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-5",
        kind: "MAIN",
        title: "Full Front Lever",
        description: "The King of Core. Hang from the bar and lift your perfectly straight body until it's parallel to the ground. Hold for 3 seconds.",
        xpReward: 300,
        goldReward: 60,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-6",
        kind: "MAIN",
        title: "The Human Flag",
        description: "Grab a vertical pole. Press with the bottom arm, pull with the top arm, and hold your body completely horizontal for 5 seconds.",
        xpReward: 300,
        goldReward: 60,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-7",
        kind: "MAIN",
        title: "Freestanding HSPU",
        description: "Kick up into a freestanding handstand (no wall) and perform 1 strict Handstand Push-up. Ultimate shoulder dominance.",
        xpReward: 250,
        goldReward: 50,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-8",
        kind: "MAIN",
        title: "One-Arm Pull-up (Negative)",
        description: "Pull yourself up with two hands, let go with one, and fight gravity all the way down. Suffer through a 5-second negative.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-9",
        kind: "MAIN",
        title: "The OAPU (One-Arm Pull-up)",
        description: "Perform 1 true, unassisted One-Arm Pull-up. You are now in the top 0.1% of athletes worldwide.",
        xpReward: 500,
        goldReward: 100,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-10",
        kind: "MAIN",
        title: "The 32kg Weighted Pull-up",
        description: "Attach a 32kg kettlebell (or roughly half your body weight) to your waist and perform 1 strict pull-up.",
        xpReward: 200,
        goldReward: 40,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-11",
        kind: "MAIN",
        title: "The 48kg Weighted Dip",
        description: "Attach 48kg (or more than half your body weight) to your waist and perform 1 strict parallel bar dip.",
        xpReward: 200,
        goldReward: 40,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-12",
        kind: "MAIN",
        title: "Endurance: 20 Unbroken Pull-ups",
        description: "Perform 20 strict, dead-hang pull-ups in a single set without dropping off the bar.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-13",
        kind: "MAIN",
        title: "Endurance: 50 Unbroken Dips",
        description: "Perform 50 strict dips in a single set. Feel your triceps beg for mercy.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-14",
        kind: "MAIN",
        title: "Legless Rope Climb",
        description: "Find a climbing rope and ascend to the top (at least 4 meters) using only your arms and back. No leg wrapping.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-15",
        kind: "MAIN",
        title: "Iron Cross Prep",
        description: "On gymnastic rings, lower yourself with straight arms as wide as you can safely go and hold for 5 seconds. Condition your bicep tendons.",
        xpReward: 200,
        goldReward: 40,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-16",
        kind: "MAIN",
        title: "Mobility: The Splits",
        description: "Achieve (or get within 2 inches of) a full front or side split. Elite strength requires elite mobility.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-17",
        kind: "MAIN",
        title: "The Gravity Combo",
        description: "String elements together: perform a Muscle-up, drop straight into a 3-second Front Lever, pull back up, and dip. Unbroken.",
        xpReward: 350,
        goldReward: 70,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-18",
        kind: "MAIN",
        title: "The 1000-Rep Week",
        description: "Accumulate a massive volume of 1000 pull-ups and push-ups combined over the course of 7 days.",
        xpReward: 250,
        goldReward: 50,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-19",
        kind: "MAIN",
        title: "Master and Apprentice",
        description: "Take someone to the park. Teach them how to perform their first pull-up or dip. Pass on the knowledge.",
        xpReward: 150,
        goldReward: 30,
        nodeSlug: "fit-n6-ascendant",
      },
      {
        slug: "fit-ascendant-20",
        kind: "MAIN",
        title: "The Ascendant Reveal",
        description: "Record a seamless flow video of your best skills. Compare it to your first wobbly push-up in Node 2. You have beaten gravity.",
        xpReward: 500,
        goldReward: 100,
        hasAiHelper: true,
        nodeSlug: "fit-n6-ascendant",
      },
    ],
    nodes: [
      { 
        slug: "fit-n1-start", 
        label: "The Starting Line", 
        statusDefault: "ACTIVE", 
        x: 104, 
        y: 8, 
        prereqs: [] 
      },
      {
        slug: "fit-n2-zero",
        label: "Zero to One",
        statusDefault: "LOCKED",
        x: 104,
        y: 140,
        prereqs: ["fit-n1-start"],
      },
      {
        slug: "fit-n3-iron",
        label: "The Path of Iron",
        statusDefault: "LOCKED",
        x: 8,
        y: 272,
        prereqs: ["fit-n2-zero"],
      },
      {
        slug: "fit-n4-gravity",
        label: "The Path of Gravity",
        statusDefault: "LOCKED",
        x: 200,
        y: 272,
        prereqs: ["fit-n2-zero"],
      },
      {
        slug: "fit-n5-ppl",
        label: "The PPL Protocol",
        statusDefault: "LOCKED",
        x: 8,
        y: 400,
        prereqs: ["fit-n3-iron"],
      },
      {
        slug: "fit-n6-vanguard",
        label: "The Iron Vanguard",
        statusDefault: "LOCKED",
        x: 8,
        y: 528,
        prereqs: ["fit-n5-ppl"],
      },
      {
        slug: "fit-n5-gravity_master",
        label: "The Gravity Master",
        statusDefault: "LOCKED",
        x: 200,
        y: 400,
        prereqs: ["fit-n4-gravity"],
      },
      {
        slug: "fit-n6-ascendant",
        label: "The Ascendant",
        statusDefault: "LOCKED",
        x: 200,
        y: 528,
        prereqs: ["fit-n5-gravity_master"],
      },
    ],
  },

  {
    slug: "culinary",
    label: "Culinary Art",
    className: "Master Chef",
    blurb: "Craft legendary meals from raw ingredients.",
    icon: "chef",
    classColor: "CRAFT",
    displayLevel: 1,
    primaryStat: "DEX",
    npcRole: "ELF",
    sortOrder: 30,
    isStarter: true,
    quests: [
      {
        slug: "cul-1",
        title: "Cook a Fresh Meal",
        description: "Prepare a balanced meal from raw ingredients.",
        xpReward: 100,
        goldReward: 25,
        hasAiHelper: true,
        nodeSlug: "cul-n2",
      },
      {
        slug: "cul-2",
        title: "Master a New Knife Cut",
        description: "Practice the julienne or brunoise technique.",
        xpReward: 60,
        nodeSlug: "cul-n2",
      },
    ],
    nodes: [
      { slug: "cul-n1", label: "Knife Skills", statusDefault: "MASTERED", x: 8, y: 8, prereqs: [] },
      {
        slug: "cul-n2",
        label: "Fresh Cooking",
        statusDefault: "ACTIVE",
        x: 8,
        y: 140,
        prereqs: ["cul-n1"],
      },
      {
        slug: "cul-n3",
        label: "Baking & Pastry",
        statusDefault: "LOCKED",
        x: 200,
        y: 140,
        prereqs: ["cul-n1"],
      },
      {
        slug: "cul-n4",
        label: "Fermentation",
        statusDefault: "LOCKED",
        x: 104,
        y: 272,
        prereqs: ["cul-n2", "cul-n3"],
      },
    ],
  },
  {
    slug: "finance",
    label: "Personal Finance",
    className: "Gold Merchant",
    blurb: "Grow your hoard and master the market.",
    icon: "coins",
    classColor: "CHA",
    displayLevel: 2,
    primaryStat: "DEX",
    npcRole: "ELF",
    sortOrder: 40,
    isStarter: false,
    quests: [
      {
        slug: "fin-1",
        title: "Track This Week's Spend",
        description: "Log every expense for 7 days in a budget sheet.",
        xpReward: 90,
        goldReward: 30,
        hasAiHelper: true,
        nodeSlug: "fin-n2",
      },
      {
        slug: "fin-2",
        title: "Read One Market Article",
        description: "Study a piece on index funds or compounding.",
        xpReward: 45,
        nodeSlug: "fin-n2",
      },
    ],
    nodes: [
      { slug: "fin-n1", label: "Budgeting", statusDefault: "MASTERED", x: 8, y: 8, prereqs: [] },
      {
        slug: "fin-n2",
        label: "Expense Tracking",
        statusDefault: "ACTIVE",
        x: 104,
        y: 140,
        prereqs: ["fin-n1"],
      },
      {
        slug: "fin-n3",
        label: "Investing 101",
        statusDefault: "LOCKED",
        x: 104,
        y: 272,
        prereqs: ["fin-n2"],
      },
    ],
  },
  {
    slug: "language",
    label: "Language Learning",
    className: "Silver Tongue",
    blurb: "Unlock new tongues and charm the realm.",
    icon: "languages",
    classColor: "CHA",
    displayLevel: 2,
    primaryStat: "CHA",
    npcRole: "ELF",
    sortOrder: 50,
    isStarter: false,
    quests: [
      {
        slug: "lang-1",
        title: "Complete a Vocab Set",
        description: "Learn 20 new words and review yesterday's set.",
        xpReward: 80,
        goldReward: 10,
        hasAiHelper: true,
        nodeSlug: "lang-n2",
      },
      {
        slug: "lang-2",
        title: "Speak for 5 Minutes",
        description: "Hold a short conversation out loud, no notes.",
        xpReward: 55,
        nodeSlug: "lang-n2",
      },
    ],
    nodes: [
      { slug: "lang-n1", label: "Alphabet", statusDefault: "MASTERED", x: 8, y: 8, prereqs: [] },
      {
        slug: "lang-n2",
        label: "Core Vocab",
        statusDefault: "ACTIVE",
        x: 104,
        y: 140,
        prereqs: ["lang-n1"],
      },
      {
        slug: "lang-n3",
        label: "Conversation",
        statusDefault: "LOCKED",
        x: 104,
        y: 272,
        prereqs: ["lang-n2"],
      },
    ],
  },
  {
    slug: "music",
    label: "Music & Instrument",
    className: "Bard",
    blurb: "Practice your craft and enchant listeners.",
    icon: "music",
    classColor: "CRAFT",
    displayLevel: 1,
    primaryStat: "CHA",
    npcRole: "ELF",
    sortOrder: 60,
    isStarter: false,
    quests: [
      {
        slug: "mus-1",
        title: "Practice Scales",
        description: "Run through major and minor scales for 15 minutes.",
        xpReward: 70,
        goldReward: 12,
        hasAiHelper: true,
        nodeSlug: "mus-n2",
      },
      {
        slug: "mus-2",
        title: "Learn a New Riff",
        description: "Memorize 8 bars of a song you love.",
        xpReward: 60,
        nodeSlug: "mus-n2",
      },
    ],
    nodes: [
      { slug: "mus-n1", label: "Music Theory", statusDefault: "MASTERED", x: 8, y: 8, prereqs: [] },
      {
        slug: "mus-n2",
        label: "Scales & Technique",
        statusDefault: "ACTIVE",
        x: 104,
        y: 140,
        prereqs: ["mus-n1"],
      },
      {
        slug: "mus-n3",
        label: "First Song",
        statusDefault: "LOCKED",
        x: 104,
        y: 272,
        prereqs: ["mus-n2"],
      },
    ],
  },
]

async function main() {
  for (const treeData of skillTrees) {

    const tree = await prisma.skillTree.upsert({
      where: { slug: treeData.slug },
      update: {
        label: treeData.label,
        className: treeData.className,
        blurb: treeData.blurb,
        icon: treeData.icon,
        classColor: treeData.classColor,
        displayLevel: treeData.displayLevel,
        primaryStat: treeData.primaryStat,
        npcRole: treeData.npcRole,
        sortOrder: treeData.sortOrder,
        isStarter: treeData.isStarter,
      },
      create: {
        slug: treeData.slug,
        label: treeData.label,
        className: treeData.className,
        blurb: treeData.blurb,
        icon: treeData.icon,
        classColor: treeData.classColor,
        displayLevel: treeData.displayLevel,
        primaryStat: treeData.primaryStat,
        npcRole: treeData.npcRole,
        sortOrder: treeData.sortOrder,
        isStarter: treeData.isStarter,
      },
    })

    const nodeBySlug = new Map()

    for (const [index, nodeData] of treeData.nodes.entries()) {
      const node = await prisma.skillNode.upsert({
        where: { slug: nodeData.slug },
        update: {
          treeId: tree.id,
          label: nodeData.label,
          statusDefault: nodeData.statusDefault,
          x: nodeData.x,
          y: nodeData.y,
          sortOrder: index,
        },
        create: {
          treeId: tree.id,
          slug: nodeData.slug,
          label: nodeData.label,
          statusDefault: nodeData.statusDefault,
          x: nodeData.x,
          y: nodeData.y,
          sortOrder: index,
        },
      })
      nodeBySlug.set(nodeData.slug, node)
    }

    for (const nodeData of treeData.nodes) {
      const node = nodeBySlug.get(nodeData.slug)
      await prisma.skillNodePrerequisite.deleteMany({
        where: { nodeId: node.id },
      })

      for (const prereqSlug of nodeData.prereqs) {
        const prerequisite = nodeBySlug.get(prereqSlug)
        await prisma.skillNodePrerequisite.create({
          data: {
            nodeId: node.id,
            prerequisiteId: prerequisite.id,
          },
        })
      }
    }

    for (const [index, questData] of treeData.quests.entries()) {
      const node = nodeBySlug.get(questData.nodeSlug)

      await prisma.quest.upsert({
        where: { slug: questData.slug },
        update: {
          treeId: tree.id,
          nodeId: node?.id,
          kind: questData.kind || "MAIN",
          title: questData.title,
          description: questData.description,
          xpReward: questData.xpReward,
          goldReward: questData.goldReward ?? 0,
          hasAiHelper: questData.hasAiHelper ?? false,
          sortOrder: index,
        },
        create: {
          treeId: tree.id,
          nodeId: node?.id,
          slug: questData.slug,
          kind: questData.kind || "MAIN",
          title: questData.title,
          description: questData.description,
          xpReward: questData.xpReward,
          goldReward: questData.goldReward ?? 0,
          hasAiHelper: questData.hasAiHelper ?? false,
          sortOrder: index,
        },
      })
    }
const definedNodeSlugs = treeData.nodes.map((n) => n.slug)
    const definedQuestSlugs = treeData.quests.map((q) => q.slug)

    const staleNodes = await prisma.skillNode.findMany({
      where: { treeId: tree.id, slug: { notIn: definedNodeSlugs } },
      select: { id: true },
    })
    const staleNodeIds = staleNodes.map((n) => n.id)

    if (staleNodeIds.length > 0) {
      await prisma.skillNodePrerequisite.deleteMany({
        where: { OR: [{ nodeId: { in: staleNodeIds } }, { prerequisiteId: { in: staleNodeIds } }] },
      })
      await prisma.quest.deleteMany({ where: { nodeId: { in: staleNodeIds } } })
      await prisma.skillNode.deleteMany({ where: { id: { in: staleNodeIds } } })
    }

    await prisma.quest.deleteMany({
      where: { treeId: tree.id, slug: { notIn: definedQuestSlugs } },
    })
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (error) => {
    console.error(error)
    await prisma.$disconnect()
    process.exit(1)
  })
